apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: schema-pod
spec:
  replicas: 1
  template:
    metadata:
      name: schema-pod
      labels:
        app: schema-pod
    spec:
      containers:
      - name: schema-pod
        image: mesosphere/bus-demo-schema:3.0.7
        command: ["sleep"]
        imagePullPolicy: Always
        args: ["1000000"]

